#!/usr/bin/env bash
# install and setup haproxy on a new Ubuntu machine
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get update
sudo apt-get install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    listen load_balancer
    	bind *:80
    	mode http
    	balance roundrobin
    	option httpclose
    	option forwardfor
    	server 29910-web-01 18.235.255.135:80 check
    	server 29910-web-02 3.94.213.38:80 check
    	option httpchk
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
