#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 26071-web-01 54.158.206.219:80 check
    server 26071-web-02 34.232.71.147:80 check
"
# Update packages
apt-get update
apt-get upgrade

# Add HAProxy PPA
apt-get install software-properties-common
add-apt-repository  ppa:vbernat/haproxy-2.5
apt-get update

# Install HAProxy
apt-get  install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
